package com.hp.it.sbs.lgms.transport.client;

import com.hp.it.sbs.core.client.interfaces.SharedBusinessService;
import com.hp.it.sbs.lgms.interfaces.LGMS;

/**
 * LGMS Composite Interface
 * Service Category:      LGMS
 * Generated By:          sbs-generator
 * Service Version:       1.0.0-SNAPSHOT
 * Core Version:          1.1.2
 * I-Processor Version:   2.1.5
 *
 * This class is generated based upon the service's interface(s).
 * The versions listed above were utilized in the process.
 * These may be snapshots instead of actual releases during development.
 */
public interface LGMSService extends SharedBusinessService, LGMS
{
	/** Service Category */
	String SERVICE_CATEGORY = "LGMS";
}
